### ISSUE TITLE
键盘遮挡textarea

### ISSUE THREAD

**Issue by FanYimin** [yicm/WxComment#1]
谢谢yicm贡献这么好的代码
键盘有时会遮挡textarea，在wxml的textarea 加入cursor-spacing='30'就好了

**Comment by yicm** [comment]
@FanYimin 感谢你的建议^_^。

**Comment by eminfan** [comment]
今天试了试，我的方法有的时候还是不行啊。有的时候还是挡住

**Comment by yicm** [comment]
那你可以再调一调，或者你可以截图给我看看是什么情况？我有空了再弄一下。

在2018年07月11日 12:06，eminfan 写道：

今天试了试，我的方法有的时候还是不行啊。有的时候还是挡住
