### ISSUE TITLE
请问报错的原因是什么

### ISSUE THREAD

**Issue by wl12345** [yicm/WxComment#10]
![_20190127122724](https://user-images.githubusercontent.com/24579523/51796496-536d7380-222f-11e9-81d9-1797765532ce.png)

**Comment by yicm** [comment]
这个表没有创建，你可以看看源码WxCommentCount的创建流程(搜索下)。

**Comment by wl12345** [comment]
请问在哪里搜，我在百度没有搜到

**Comment by yicm** [comment]
项目里搜。。
