### ISSUE TITLE
希望大佬能帮我解答一下问题，谢谢~

### ISSUE THREAD

**Issue by hjs557523** [yicm/WxComment#16]
（1）我每次点进博主的文章，我都必须填写评论提交之后，我才能看到所有人对这篇文章的评论，然后我再退出去，再重新进入这篇文章，所有的评论又不见了，又必须重新提交评论才能看到。
（2）关于设置adminId，我想问一下是这里是填_User表的username呢？还是objectId？还是openId？

**Comment by yicm** [comment]
@hjs557523 （1）有时候是网络的问题会导致拉取不到leancloud数据库里的信息，这个可能超时要处理下。 （2） 这个你都可以去试下哦，不过我readme里好像截图了吧
