### ISSUE TITLE
如果能够用小程序云API就好了

### ISSUE THREAD

**Issue by xiaobear250** [yicm/WxComment#17]
如题，小程序现在也有免费的云开发支持，如果可以用小程序的云来整合就更好了。无缝对接。

**Comment by yicm** [comment]
@xiaobear250  这个可以有哦，不过做这个插件只是一时兴起。另外目前来说，leancloud的api相对小程序来说更加丰富和友好哈，而且免费版本对于个人也是足够用了，转成商用版也不是很贵。
