### ISSUE TITLE
手机端

### ISSUE THREAD

**Issue by WinterSaber** [yicm/WxComment#19]
大佬，问一下，为什么这个评论功能在编译器上可以正常显示，在手机端就一直是无法加载评论呀，求解答。

**Comment by WinterSaber** [comment]
我今天又试了一遍，发现是在手机端调试的时候可以显示评论功能正常使用，但是预览的时候不可以使用。具体原因还是不了解，希望大佬能帮帮忙。

**Comment by yicm** [comment]
@WinterSaber 最近leancloud域名挂了，现在应该恢复了。
