### ISSUE TITLE
在跳转页面引用组件发生这个问题

### ISSUE THREAD

**Issue by IXIXVI** [yicm/WxComment#2]
thirdScriptError 
 sdk uncaught third Error 
 module "pages/techers_detail/teachers_detail.js" is not defined 
 Error: module "pages/techers_detail/teachers_detail.js" is not defined
    at require (http://127.0.0.1:31928/appservice/__dev__/WAService.js:19:19934)
    at http://127.0.0.1:31928/appservice/appservice?t=1536501109776:1037:9
console.error @ VM8793:1
(anonymous) @ WAService.js:14
(anonymous) @ WAService.js:5
a @ appservice?t=1536501109776:1022
window.onerror @ VM8793:1

可以请教一下吗，多谢

**Comment by yicm** [comment]
错误很明显哈，你仔细看下错误提示去调试下。
