### ISSUE TITLE
按照Readme配置好服务器，但是显示Error: Unauthorized. [401 POST https://wxf05adb.api.lncld.net/1.1/users]

### ISSUE THREAD

**Issue by ghost** [yicm/WxComment#5]
av-weapp-min.js:21 Error: Unauthorized. [401 POST https://wxf05adb.api.lncld.net/1.1/users]
    at av-weapp-min.js:2
    at A (av-weapp-min.js:21)
    at C (av-weapp-min.js:21)
    at E (av-weapp-min.js:21)
    at b (av-weapp-min.js:21)
    at Function.u (av-weapp-min.js:21)
    at [publib]:1
    at Timeout._onTimeout ([publib]:1)
    at ontimeout (timers.js:471)
    at tryOnTimeout (timers.js:306)

**Comment by ghost** [comment]
这是报错截图
![1](https://user-images.githubusercontent.com/22796957/48968414-6a72c800-f02a-11e8-96fb-38cdc9e87b2c.JPG)

**Comment by ylqylq001** [comment]
这是我配置好的服务器
AppId和AppSecret也已经配置完毕
![0](https://user-images.githubusercontent.com/22796957/48968431-ac037300-f02a-11e8-9a99-8435b7e3c33e.JPG)

**Comment by ylqylq001** [comment]
组件能正常显示，但无法发送消息
![3](https://user-images.githubusercontent.com/22796957/48968515-8a56bb80-f02b-11e8-8992-6afe0090e71f.JPG)

**Comment by ylqylq001** [comment]
组件能正常显示，但无法发送消息
![3](https://user-images.githubusercontent.com/22796957/48968548-0224e600-f02c-11e8-80ee-b09d3f205d5b.JPG)

**Comment by ghost** [comment]
组件能正常显示，但无法发送消息

**Comment by yicm** [comment]
你是不是没有将leancloud域名加入到微信服务器配置中？

**Comment by ylqylq001** [comment]
> 你是不是没有将leancloud域名加入到微信服务器配置中？
完全按照Readme上的步骤操作，但是错误仍然存在
小程序域名白名单已配置好，参见下图：
![1](https://user-images.githubusercontent.com/22796957/49063193-90c67c80-f251-11e8-8e13-78a386e562c5.PNG)
![2](https://user-images.githubusercontent.com/22796957/49063195-90c67c80-f251-11e8-8d9e-412eebb42ecd.PNG)

**Comment by yicm** [comment]
你是不是leancloud的权限相关的key或者密钥输错了？

**Comment by ghost** [comment]
> 你是不是leancloud的权限相关的key或者密钥输错了？
检查过了，没有输错

**Comment by ghost** [comment]
算了算了，已经过去这么久了
我已经自己写好了一个后台来实现评论功能
谢谢回复 ：）

**Comment by chenyuruoyu** [comment]
同样报这个错误
