### ISSUE TITLE
显示 https://wx185ca1.api.lncld.net 不在以下 request 合法域名列表中

### ISSUE THREAD

**Issue by Eattttt** [yicm/WxComment#6]
**错误提示**
1. https://wx185ca1.api.lncld.net 不在以下 request 合法域名列表中
2.request:fail url not in domain list
3.VM136:1 Error: Request has been terminated
4.GET https://app-router.leancloud.cn/2/route?appId=wx185ca16caa2de38b 400 (Bad Request)

_https://leancloud.cn/docs/weapp-domains.html_ 
app-router.leancloud.cn
re4ek1a3.api.lncld.net
re4ek1a3.engine.lncld.net
re4ek1a3.rtm.lncld.net
上面是LeanCloud 应用提供request 域名，我除了uploadFile和downloadFile全部都添加到我小程序的设置里了。appid和appKey也都按readme里面设置了。

**Comment by Eattttt** [comment]
appid和appKey
与小程序的那个搞错了

**Comment by chenyuruoyu** [comment]
什么意思 我的也报这样的错误 能说一下怎么解决的的吗？
